"""Every code token in the orientation docs names something that exists (#208).

WHAT: the docs are README.md, CONTRIBUTING.md and every tracked CONTEXT.md (`_docs()`). A
token is a backticked span outside a fenced block, or a whole line inside one; a `<name>`
placeholder in it is read as `*`. Each token is judged by kind:
  path    `a/b`, `x.py` (a code extension), a glob: a tracked file or directory, found from
          the repository root or from the doc's own directory (tests/CONTEXT.md writes
          `modal/` for tests/modal/); a glob must match one; a bare file name must be the
          name of a tracked file. A key of cs2rl.eval.metrics_schema.REGISTRY (`game/*`)
          is a metric column, not a path.
  module  `python -m X` and a backticked `cs2rl.a.b`: a cs2rl name must resolve the way
          tests/integration/test_name_strings_resolve.py's `dotted_problem` resolves one
          (a tracked module, or a module plus an attribute); another top-level name must
          be named in pyproject.toml or be a standard-library module.
  flag    `--x` after `-m cs2rl.train`: an option `python -m cs2rl.train --help` prints.
  head    HEAD_*: a member of `enum ActionHead` in cs2_types.h.
  array   a doc's `ACTION_HEAD_SIZES[] = {...}` or NAMES: equal to the header's.
  zigstep `zig build <step>`: a `b.step` in build.zig.
  marker  `-m "not X"`: a marker tests/conftest.py registers.
  ident   any other backticked identifier: a word in some tracked file that is not markdown.
OUT, counted and never checked: an absolute or home path, a URL, a path that climbs out of
the checkout, and a path with a component the tracked .gitignore ignores by plain name
(`.venv`, `outputs`, `zig-out`). The local .git/info/exclude is never read: it differs
between clones, and it is what hides the owner's docs/ here.
ALLOW: the tokens that name nothing in the repository by design, each with its reason. The
set is watched: an entry no token uses fails test_every_allow_entry_is_used, so a doc edit
cannot leave a dead allowance behind, and deleting an entry makes its token fail.

WHY: #199 and #205 moved modules and left 14 stale tokens in CONTRIBUTING.md and readme.md,
found by hand in #291. tests/integration/test_name_strings_resolve.py reads only the strings
of .py and C files, and no other test reads the docs.

LIMITS:
  - A bare file name resolves if ANY tracked file has that name, and an ident if the word
    occurs anywhere outside markdown: the pin catches a name that no longer exists, not one
    that now means something else.
  - File names with other extensions (`.json`, `.jsonl`, `.npy`) and prose outside backticks
    and fences are not read. A flag is checked only after `-m cs2rl.train`.
  - Commands are not run: their module, trainer flags, zig step and marker are resolved.
  - A doc outside `_docs()` (AGENTS.md, deploy/serversetup.md) is not read, and a code span
    must sit on one line (test_no_code_span_crosses_a_line).
"""

from __future__ import annotations

import fnmatch
import os
import re
import subprocess
import sys
from functools import cache
from pathlib import Path

import pytest

from tests.conftest import REPO_ROOT
from tests.integration.test_name_strings_resolve import dotted_problem

HEADER = REPO_ROOT / "src" / "cs2rl" / "env" / "c" / "cs2_types.h"
BUILD_ZIG = REPO_ROOT / "src" / "cs2rl" / "env" / "c" / "build.zig"

# Tokens that name nothing in the repository by design. Each needs a reason, and each must
# still be used by some doc (test_every_allow_entry_is_used).
ALLOW = {
    "HEAD_NEWHEAD": "CONTRIBUTING.md's placeholder for the head being added",
    "nav_data.h": "generated by scripts/bake_nav.py into src/cs2rl/env/c/, untracked",
    "tests/env-c/": "tests/CONTEXT.md's example of a directory the layout guard cannot walk",
    "spec/": "tests/CONTEXT.md: the test directory a spec test would create does not exist yet",
    "runs/...": "a path on the Modal Volume, not in the repository",
}

_CODE_EXT = r"(?:py|h|c|cs|md|sh|toml|zig|zon|so|txt)"
_PATH = re.compile(r"(?<![\w./~-])((?:~|\.{1,2})?/?[\w.~-]+(?:/[\w.*~-]*)+|[\w-]+\." + _CODE_EXT +
                   r")(?![\w/])")
_HOOKS = re.compile(r"core\.hooksPath (\S+)")
_PY_M = re.compile(r"python -m ([\w.]+)")
_FLAGS = re.compile(r"-m cs2rl\.train((?:\s+--[\w-]+)+)")
_HEAD = re.compile(r"\bHEAD_\w+")
_ARRAY = re.compile(r"ACTION_HEAD_(SIZES|NAMES)\[\]\s*=\s*\{([^}]*)\}", re.S)
_ZIG_STEP = re.compile(r"(?:ziglang|zig) build ([\w-]+)")
_MARKER = re.compile(r"-m ['\"]not (\w+)['\"]")
_BACKTICK = re.compile(r"`([^`\n]+)`")
_PLACEHOLDER = re.compile(r"<[^<>\s]+>")
_IDENT = re.compile(r"(?:#define )?([A-Za-z_]\w*)(?:\(\))?(?:\[\])?")
_DUNDER = re.compile(r"__\w+__")


@cache
def _tracked() -> tuple[frozenset[str], frozenset[str]]:
    """(tracked files, their directories and every ancestor), from `git ls-files`."""
    files = subprocess.run(["git", "ls-files"],
                           cwd=REPO_ROOT,
                           capture_output=True,
                           text=True,
                           check=True).stdout.splitlines()
    dirs = set()
    for f in files:
        parent = os.path.dirname(f)
        while parent:
            dirs.add(parent)
            parent = os.path.dirname(parent)
    return frozenset(files), frozenset(dirs)


def _docs() -> list[str]:
    """The docs this pin reads: README.md, CONTRIBUTING.md and every tracked CONTEXT.md."""
    files, _ = _tracked()
    return ["README.md", "CONTRIBUTING.md"] + sorted(f
                                                     for f in files if Path(f).name == "CONTEXT.md")


@cache
def _basenames() -> frozenset[str]:
    return frozenset(Path(f).name for f in _tracked()[0])


@cache
def _ignored_names() -> frozenset[str]:
    """Plain names (`outputs`, `zig-out/`) the tracked .gitignore ignores at any depth."""
    lines = (REPO_ROOT / ".gitignore").read_text().splitlines()
    return frozenset(line.strip().rstrip("/") for line in lines
                     if re.fullmatch(r"[\w.-]+/?", line.strip()))


_THIS_FILE = Path(__file__).resolve().relative_to(REPO_ROOT.resolve()).as_posix()


@cache
def _words() -> frozenset[str]:
    """Every word in a tracked file that is not markdown, as `git grep -w` would see it.

    This file is left out, so that its own ALLOW keys and controls cannot vouch for a doc.
    """
    words: set[str] = set()
    for f in _tracked()[0]:
        if f.endswith(".md") or f == _THIS_FILE:
            continue
        try:
            words.update(re.findall(r"\w+", (REPO_ROOT / f).read_text(errors="ignore")))
        except (IsADirectoryError, FileNotFoundError):
            continue                   # a tracked symlink to a directory, or a deleted file
    return frozenset(words)


@cache
def _train_options() -> frozenset[str]:
    """Every long option `python -m cs2rl.train --help` prints (the reward flags are generated)."""
    out = subprocess.run([sys.executable, "-m", "cs2rl.train", "--help"],
                         cwd=REPO_ROOT,
                         capture_output=True,
                         text=True,
                         timeout=120,
                         check=True).stdout
    return frozenset(re.findall(r"(?<![\w-])(--[\w-]+)", out))


@cache
def _header_text() -> str:
    return HEADER.read_text()


@cache
def _metric_keys() -> frozenset[str]:
    from cs2rl.eval.metrics_schema import REGISTRY
    return frozenset(REGISTRY)


def _path_verdict(token: str, doc_dir: str) -> tuple[str, str]:
    files, dirs = _tracked()
    t = token[2:] if token.startswith("./") else token
    t = t.rstrip("/")
    if token in ALLOW or t in ALLOW:
        return "ALLOW", ALLOW.get(token) or ALLOW[t]
    if t.startswith(("/", "~")) or "://" in t:
        return "OUT", "absolute or home path"
    if t in _metric_keys():
        return "OK", "metric key"
    candidates = [os.path.normpath(os.path.join(base, t)) for base in dict.fromkeys((".", doc_dir))]
    candidates = [c for c in candidates if c != ".." and not c.startswith("../")]
    if not candidates:
        return "OUT", "climbs out of the checkout"
    if any(part in _ignored_names() for c in candidates for part in c.split("/")):
        return "OUT", "under a directory .gitignore ignores"
    for c in candidates:
        if "*" in c:
            if any(fnmatch.fnmatchcase(p, c) for p in files | dirs):
                return "OK", f"glob {c}"
        elif c in files or c in dirs:
            return "OK", c
    if "/" not in t and "*" not in t and t in _basenames():
        return "OK", f"name of a tracked file: {t}"
    return "STALE", f"not a tracked file or directory (tried {candidates})"


def _module_verdict(name: str) -> tuple[str, str]:
    name = name.rstrip(".")
    top = name.split(".")[0]
    if top == "cs2rl":
        problem = dotted_problem(name)
        return ("OK", "cs2rl name") if problem is None else ("STALE", problem)
    if top in ("tests", "scripts"):
        rel = name.replace(".", "/")
        files, dirs = _tracked()
        return ("OK", rel) if f"{rel}.py" in files or rel in dirs else ("STALE", f"no {rel}.py")
    if top in sys.stdlib_module_names:
        return "OK", "standard library"
    named = re.search(r'"' + re.escape(top) + r'[>=<~!"]',
                      (REPO_ROOT / "pyproject.toml").read_text())
    return ("OK", "named in pyproject.toml") if named else ("STALE", "not named in pyproject.toml")


def census(doc: str, text: str) -> list[tuple[int, str, str, str, str]]:
    """(line, kind, token, verdict, detail) for every token of `text`, read as the doc `doc`.

    `doc` is a repo-relative path; only its directory is used, for relative paths.
    """
    doc_dir = os.path.dirname(doc) or "."
    header = _header_text()
    enum = re.search(r"enum ActionHead \{(.*?)\};", header, re.S)
    assert enum, f"no `enum ActionHead` in {HEADER}"
    heads = set(re.findall(r"\b(HEAD_\w+)\s*=", enum.group(1)))
    steps = set(re.findall(r'b\.step\(\s*"([\w-]+)"', BUILD_ZIG.read_text()))
    conftest = (REPO_ROOT / "tests" / "conftest.py").read_text()
    rows = []
    in_block = False
    for i, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith("```"):
            in_block = not in_block
            continue
        for raw in [line] if in_block else _BACKTICK.findall(line):
            span = _PLACEHOLDER.sub("*", raw)
            for m in dict.fromkeys(m.group(1) for m in _PATH.finditer(span)):
                if not m.startswith("//") and not re.fullmatch(r"[\d.]+", m):
                    rows.append((i, "path", m, *_path_verdict(m, doc_dir)))
            for m in _HOOKS.finditer(span):
                rows.append((i, "path", m.group(1), *_path_verdict(m.group(1), doc_dir)))
            for m in _PY_M.finditer(span):
                rows.append((i, "module", m.group(1), *_module_verdict(m.group(1))))
            for m in _FLAGS.finditer(span):
                for flag in m.group(1).split():
                    ok = flag in _train_options()
                    rows.append(
                        (i, "flag", flag, "OK" if ok else "STALE", "an option of cs2rl.train"
                         if ok else "not an option of `python -m cs2rl.train`"))
            for h in _HEAD.findall(span):
                verdict = "ALLOW" if h in ALLOW else "OK" if h in heads else "STALE"
                rows.append((i, "head", h, verdict, ALLOW.get(h, "enum ActionHead")))
            for m in _ZIG_STEP.finditer(span):
                ok = m.group(1) in steps
                rows.append(
                    (i, "zigstep", m.group(1), "OK" if ok else "STALE", "b.step in build.zig"))
            for m in _MARKER.finditer(span):
                ok = f'"{m.group(1)}:' in conftest
                rows.append(
                    (i, "marker", m.group(1), "OK" if ok else "STALE", "registered in conftest"))
            if in_block:
                continue
            token = span.strip()
            if _DUNDER.fullmatch(token):
                continue
            if re.fullmatch(r"cs2rl(?:\.\w+)+", token):
                rows.append((i, "module", token, *_module_verdict(token)))
                continue
            ident = _IDENT.fullmatch(token)
            if ident and not _HEAD.fullmatch(ident.group(1)) and not _PATH.fullmatch(token):
                word = ident.group(1)
                if word in ALLOW:
                    rows.append((i, "ident", word, "ALLOW", ALLOW[word]))
                elif word in _words():
                    rows.append((i, "ident", word, "OK", "word in a tracked file"))
                else:
                    rows.append(
                        (i, "ident", word, "STALE", "no tracked file outside markdown has it"))
    for m in _ARRAY.finditer(text):
        doc_list = [s.strip() for s in m.group(2).split(",") if s.strip()]
        hm = re.search(r"ACTION_HEAD_" + m.group(1) + r"\[\]\s*=\s*\{([^}]*)\}", header, re.S)
        assert hm, f"no ACTION_HEAD_{m.group(1)}[] in {HEADER}"
        header_list = [s.strip() for s in hm.group(1).split(",") if s.strip()]
        line = text[:m.start()].count("\n") + 1
        if doc_list == header_list:
            rows.append((line, "array", "ACTION_HEAD_" + m.group(1), "OK", "equals the header"))
        else:
            rows.append((line, "array", "ACTION_HEAD_" + m.group(1), "STALE",
                         f"doc {doc_list} != header {header_list}"))
    return rows


@cache
def _all_rows() -> tuple[tuple[str, int, str, str, str, str], ...]:
    return tuple(
        (doc, *row) for doc in _docs() for row in census(doc, (REPO_ROOT / doc).read_text()))


def test_the_docs_are_found_and_read():
    """A false zero looks like a clean pass: the doc set and every doc's token count have floors."""
    docs = _docs()
    assert {"README.md", "CONTRIBUTING.md", "tests/CONTEXT.md"} <= set(docs), docs
    assert len(docs) >= 8, docs
    per_doc = {doc: sum(1 for row in _all_rows() if row[0] == doc) for doc in docs}
    assert all(n >= 20 for n in per_doc.values()), per_doc
    kinds = {row[2] for row in _all_rows()}
    assert {"path", "module", "flag", "head", "array", "zigstep", "marker", "ident"} <= kinds, kinds


def test_every_doc_token_resolves():
    stale = [row for row in _all_rows() if row[4] == "STALE"]
    assert not stale, "stale tokens in the docs (fix the doc, or ALLOW a token that names nothing by design):\n" + "\n".join(
        f"  {doc}:{line} {kind} `{token}`: {detail}" for doc, line, kind, token, _, detail in stale)


def test_no_code_span_crosses_a_line():
    """A code span split over two lines is read as two broken spans, so its tokens go unchecked."""
    broken = []
    for doc in _docs():
        in_block = False
        for i, line in enumerate((REPO_ROOT / doc).read_text().splitlines(), 1):
            if line.lstrip().startswith("```"):
                in_block = not in_block
            elif not in_block and line.count("`") % 2:
                broken.append(f"{doc}:{i}")
    assert not broken, f"keep each `code span` on one line: {broken}"


def test_every_allow_entry_is_used():
    used = {row[3] for row in _all_rows() if row[4] == "ALLOW"}
    used |= {row[3].removeprefix("./").rstrip("/") for row in _all_rows() if row[4] == "ALLOW"}
    unused = sorted(k for k in ALLOW if k not in used and k.rstrip("/") not in used)
    assert not unused, f"ALLOW entries no doc token uses any more; delete them: {unused}"


@pytest.mark.parametrize(
    "doc, text, kind",
    [
        ("README.md", "`scripts/no_such_tool.py`", "path"),
        ("README.md", "`modal/`", "path"),
        ("README.md", "`no_such_tool_208.py`", "path"),
        ("README.md", "`python -m no_such_package_208`", "module"),
        ("README.md", "`python -m cs2rl.train --no-such-flag`", "flag"),
        ("README.md", "`HEAD_NO_SUCH_HEAD`", "head"),
        ("README.md", "`zig build no_such_step`", "zigstep"),
        ("README.md", "`-m \"not no_such_marker\"`", "marker"),
        ("README.md", "`no_such_ident" + "ifier_208`", "ident"),            # composed: the word is in no file
        ("README.md", "```c\nACTION_HEAD_SIZES[] = {9, 2};\n```", "array"),
    ])
def test_a_stale_token_of_each_kind_is_caught(doc, text, kind):
    rows = census(doc, text)
    assert [(r[1], r[3]) for r in rows if r[1] == kind] == [(kind, "STALE")], rows


@pytest.mark.parametrize("doc, token, verdict", [
    ("tests/CONTEXT.md", "modal/", "OK"),
    ("README.md", "tests/conftest.py", "OK"),
    ("README.md", "scripts/modal_*", "OK"),
    ("README.md", "tests/modal/test_modal_<module>.py", "OK"),
    ("README.md", "game/*", "OK"),
    ("README.md", "~/.awpy/navs/", "OUT"),
    ("README.md", ".venv/bin/python", "OUT"),
    ("README.md", "../usr/include", "OUT"),
])
def test_what_resolves_and_what_is_out_of_scope(doc, token, verdict):
    rows = [r for r in census(doc, f"`{token}`") if r[1] == "path"]
    assert [r[3] for r in rows] == [verdict], rows
