"""cs2rl: the CS2 reinforcement-learning environment, trainer and tools, as one package.

Importing it runs one check, `_refuse_a_foreign_checkout`, and nothing else.

WHY the check exists (#199, verifier findings V1 and N1): worktrees borrow main's
.venv, whose editable install is a .pth naming ONE checkout's src/ (main's). A
worktree process that does not put its own src/ first on PYTHONPATH (`python -m
cs2rl.train`, `scripts/*.py`) therefore imports MAIN's cs2rl and runs main's code
with no error: demos stamped with the worktree's commit but generated by main's
env, a nav_data.h baked from main's map.

WHAT it compares: the checkout this package was imported from, and the checkout
the process belongs to. A checkout is a directory holding pyproject.toml and
src/cs2rl/__init__.py; the process's checkout is the nearest one at or above:
  - the script's directory, when sys.argv[0] is a `.py` path outside site-packages
    (`python path/to/x.py`, from any working directory);
  - otherwise the working directory. This is the case for `-m` (runpy imports
    the package while sys.argv[0] is still '-m'), `-c`, the interactive prompt,
    console scripts such as `.venv/bin/pytest` (no `.py` suffix) and `python -m
    pytest` (sys.argv[0] is pytest's __main__.py in site-packages).
Different checkouts: ImportError, naming both and both remedies.

WHAT it does NOT cover (it stays silent):
  - An installed copy (the Modal wheel): this file sits in site-packages, not
    in a src/ beside a pyproject.toml, so there is no checkout to compare. The
    Modal working directory is the extracted archive, which IS a checkout copy.
  - A process whose script or working directory is in no checkout (`cd /tmp &&
    python -m cs2rl.train`): nothing says which checkout was meant.
  - The pytest tripwire (tests/conftest.py) remains the only check of what else
    a session's sys.path holds.

PITFALLS:
  - `.py` only, and never under site-packages: a worktree's .venv is a symlink
    to main's, so `.venv/bin/pytest` and pytest's __main__.py resolve into MAIN.
    Walking up from them would refuse every worktree test run once main is a
    checkout.
  - A relative sys.argv[0] is resolved against the working directory at import
    time. A script that os.chdir()s before its first `import cs2rl` would be
    judged by the wrong directory (no script here does).
  - os.path.samefile, not string compare: this drive is mounted under two names.
  - Any OSError (deleted cwd, unreadable parent) skips the check rather than
    breaking the import.
  - os.path, not pathlib: pathlib drags in ~25 modules (re, enum, urllib, ...),
    ~13 ms that `import cs2rl` would otherwise not pay (0.3 ms with os.path, which
    is already loaded at interpreter start).
"""


def _refuse_a_foreign_checkout() -> None:
    import os
    import sys

    def is_checkout(d: str) -> bool:
        return (os.path.isfile(os.path.join(d, "pyproject.toml"))
                and os.path.isfile(os.path.join(d, "src", "cs2rl", "__init__.py")))

    package = os.path.dirname(os.path.realpath(__file__))
    root = os.path.dirname(os.path.dirname(package))
    # An installed copy (site-packages) is not a source checkout: nothing to compare.
    if (os.path.basename(os.path.dirname(package)) != "src"
            or not os.path.isfile(os.path.join(root, "pyproject.toml"))):
        return
    # `getattr`: an embedded interpreter may have no sys.argv at all.
    argv0 = (getattr(sys, "argv", None) or [""])[0]
    by_script = argv0.endswith(".py") and "site-packages" not in argv0.split(os.sep)
    try:
        start = os.path.realpath(
            os.path.dirname(os.path.abspath(argv0)) if by_script else os.getcwd())
        # Walk up to the nearest checkout; none up to the filesystem root: silent.
        checkout = start
        while not is_checkout(checkout):
            parent = os.path.dirname(checkout)
            if parent == checkout:
                return
            checkout = parent
        if os.path.samefile(checkout, root):
            return
    except OSError:
        return
    if by_script:
        what = f"the script {argv0}"
        own = os.path.normpath(
            os.path.join(root, os.path.relpath(start, checkout), os.path.basename(argv0)))
        other_remedy = f"run {root}'s copy of the script instead: {own}"
    else:
        what = "the working directory"
        other_remedy = f"cd {root} first"
    raise ImportError(
        f"cs2rl was imported from {package}, but {what} is inside another checkout, "
        f"{checkout}. The shared .venv's editable install names one checkout's src/, so this "
        f"process would silently run {root}'s code. To run {checkout}'s code instead, put its "
        f"src/ first on PYTHONPATH:\n    env PYTHONPATH={os.path.join(checkout, 'src')} <command>\n"
        f"To run {root}'s code, {other_remedy}")


_refuse_a_foreign_checkout()
