"""cs2rl: the CS2 reinforcement-learning environment, trainer and tools, as one package.

Importing it runs one check, `_refuse_a_foreign_checkout`, and nothing else.

WHY the check exists (#199, verifier finding V1): worktrees borrow main's .venv,
whose editable install is a .pth naming ONE checkout's src/ (main's). A process
started in a worktree without that worktree's src/ first on PYTHONPATH (`python
-m cs2rl.train`, `scripts/*.py`) therefore imports MAIN's cs2rl and runs main's
code with no error: demos stamped with the worktree's commit but generated by
main's env, a nav_data.h baked from main's map. The pytest tripwire
(tests/conftest.py) covers only pytest; this covers every entry point.

WHAT it compares: the checkout this package was imported from, and the nearest
checkout at or above the working directory (a directory holding pyproject.toml
and src/cs2rl/__init__.py). Different checkouts: ImportError, naming both.

PITFALLS:
  - The working directory, never sys.argv[0]: a worktree's .venv is a symlink to
    main's, so `.venv/bin/pytest` resolves into main.
  - Silent for an installed wheel (the Modal path: this file sits in
    site-packages, and the working directory is the extracted archive, which IS
    a checkout copy) and when the working directory is in no checkout.
  - os.path.samefile, not string compare: this drive is mounted under two names.
  - Any OSError (deleted cwd, unreadable parent) skips the check rather than
    breaking the import.
"""


def _refuse_a_foreign_checkout() -> None:
    import os
    from pathlib import Path

    package = Path(__file__).resolve().parent
    root = package.parents[1]
    # An installed copy (site-packages) is not a source checkout: nothing to compare.
    if package.parent.name != "src" or not (root / "pyproject.toml").is_file():
        return
    try:
        cwd = Path.cwd().resolve()
        marks = ("pyproject.toml", "src/cs2rl/__init__.py")
        checkout = next((d for d in (cwd, *cwd.parents) if all((d / m).is_file() for m in marks)),
                        None)
        if checkout is None or os.path.samefile(checkout, root):
            return
    except OSError:
        return
    raise ImportError(
        f"cs2rl was imported from {package}, but the working directory is inside another "
        f"checkout, {checkout}. The shared .venv's editable install names one checkout's src/, "
        f"so this process would silently run {root}'s code. Put the working checkout's src/ "
        f"first on PYTHONPATH:\n    env PYTHONPATH={checkout / 'src'} <command>")


_refuse_a_foreign_checkout()
