#!/usr/bin/env python3
"""bake_nav.py — Generate src/cs2rl/c_env/nav_data.h from make_simple_map().

Run: uv run python scripts/bake_nav.py
Re-run whenever env/map.py or SIMPLE_ROOMS changes.
"""
import numpy as np

from cs2rl.env.c import SOURCE_DIR
from cs2rl.env.map import SIMPLE_ROOMS, make_simple_map
from cs2rl.env.nav import (
    _DELTA_VECTORS,
    _DIR_FACING,
    BOMB_DEFUSE_TIME,
    BOMB_PLANT_TIME,
    BOMB_TIMER,
    ENEMY_MEMORY_TICKS,
    FOOTSTEP_RADIUS,
    GUNSHOT_RADIUS,
    LASER_DAMAGE,
    LASER_RANGE,
    MAX_TURN_SPEED_RAD,
    ROUND_TIME,
    SHOOT_COOLDOWN,
    STALE_MEMORY_TICK,
)

md = make_simple_map()


def _arr_float(arr, name):
    flat = np.asarray(arr, dtype=np.float32).flatten()
    vals = ", ".join(f"{v:.6f}f" for v in flat)
    return f"static const float {name}[{len(flat)}] = {{{vals}}};\n"


def _arr_int32(arr, name):
    flat = np.asarray(arr, dtype=np.int32).flatten()
    vals = ", ".join(str(v) for v in flat)
    return f"static const int32_t {name}[{len(flat)}] = {{{vals}}};\n"


def _arr_int8(arr, name):
    flat = np.asarray(arr, dtype=np.int8).flatten()
    vals = ", ".join(str(v) for v in flat)
    return f"static const int8_t {name}[{len(flat)}] = {{{vals}}};\n"


# Area bounds: [N * 4] = [x0, y0, x1, y1] per area (from SIMPLE_ROOMS)
area_bounds = np.zeros((md.N, 4), dtype=np.float32)
for idx, x0, y0, x1, y1, *_ in SIMPLE_ROOMS:           # *_ absorbs z, is_ramp (7-tuple schema)
    area_bounds[idx] = [x0, y0, x1, y1]

# Spawn area_ids → area_idx (area_id == area_idx for simple map)
t_spawns = np.array(md.t_spawn_areas, dtype=np.int32)
ct_spawns = np.array(md.ct_spawn_areas, dtype=np.int32)

# delta_x / delta_y from _DELTA_VECTORS (9 entries)
delta_x = np.array([_DELTA_VECTORS[k][0] for k in sorted(_DELTA_VECTORS)], dtype=np.float32)
delta_y = np.array([_DELTA_VECTORS[k][1] for k in sorted(_DELTA_VECTORS)], dtype=np.float32)
dir_facing = np.array([_DIR_FACING[k] for k in sorted(_DIR_FACING)], dtype=np.float32)

grid_flat = md.grid.astype(np.int32).flatten()         # row-major [H * W]
vis_flat = md.vis_matrix.astype(np.int8).flatten()
adj_flat = md.adjacency.astype(np.int8).flatten()
cxy_flat = md.centroids.astype(np.float32).flatten()   # [N * 2]
aids_flat = md.area_ids.astype(np.int32).flatten()
bm_flat = md.bombsite_mask.astype(np.int8).flatten()
bi_flat = md.bombsite_by_idx.astype(np.int8).flatten()
bd_flat = md.bombsite_dist.astype(np.float32).flatten()
                                                       # Verticality batch: per-area terrain elevation + ramp flag.
                                                       # centroids_z is the TOP elevation for ramps (e.g., a 0→64 ramp stores 64).
                                                       # is_ramp is bool — convert to int8 for nav_data.h consistency with bombsite_mask.
cz_flat = md.centroids_z.astype(np.float32).flatten()  # [N]
isr_flat = md.is_ramp.astype(np.int8).flatten()        # [N]

H, W = md.grid.shape

lines = [
    "/* nav_data.h — AUTO-GENERATED by scripts/bake_nav.py. DO NOT EDIT. */\n",
    "#pragma once\n",
    "#include <stdint.h>\n",
    "\n",
    f"#define NAV_N              {md.N}\n",
    f"#define NAV_GRID_W         {W}\n",
    f"#define NAV_GRID_H         {H}\n",
    f"#define NAV_MAX_AREA_ID    {int(md.area_ids.max())}\n",
    f"#define NAV_GRID_X_MIN     {md.grid_x_min:.6f}f\n",
    f"#define NAV_GRID_Y_MIN     {md.grid_y_min:.6f}f\n",
    f"#define NAV_GRID_INV_CELL  {1.0/md.grid_cell_size:.6f}f\n",
    f"#define NAV_X_MIN          {md.x_min:.6f}f\n",
    f"#define NAV_X_MAX          {md.x_max:.6f}f\n",
    f"#define NAV_Y_MIN          {md.y_min:.6f}f\n",
    f"#define NAV_Y_MAX          {md.y_max:.6f}f\n",
    f"#define NAV_INV_X_RANGE    {1.0/(md.x_max-md.x_min):.6f}f\n",
    f"#define NAV_INV_Y_RANGE    {1.0/(md.y_max-md.y_min):.6f}f\n",
    f"#define NAV_X_OFFSET       {md.x_min:.6f}f\n",
    f"#define NAV_Y_OFFSET       {md.y_min:.6f}f\n",
    f"#define NAV_BOMBSITE_DIST_SCALE {md.bombsite_dist_scale:.6f}f\n",
    f"#define NAV_N_T_SPAWNS     {len(t_spawns)}\n",
    f"#define NAV_N_CT_SPAWNS    {len(ct_spawns)}\n",
                                                                                # Game constants
    f"#define CFG_LASER_DAMAGE   {LASER_DAMAGE}\n",
    f"#define CFG_LASER_RANGE    {float(LASER_RANGE):.6f}f\n",
    f"#define CFG_LASER_RANGE_SQ {float(LASER_RANGE)**2:.6f}f\n",
    f"#define CFG_SHOOT_COOLDOWN {SHOOT_COOLDOWN}\n",
    f"#define CFG_BOMB_PLANT_TIME  {BOMB_PLANT_TIME}\n",
    f"#define CFG_BOMB_DEFUSE_TIME {BOMB_DEFUSE_TIME}\n",
    f"#define CFG_BOMB_DEFUSE_KIT  {BOMB_DEFUSE_TIME // 2}\n",
    f"#define CFG_BOMB_TIMER       {BOMB_TIMER}\n",
    f"#define CFG_ROUND_TIME       {ROUND_TIME}\n",
    f"#define CFG_FOOTSTEP_RADIUS_SQ {float(FOOTSTEP_RADIUS)**2:.6f}f\n",
    f"#define CFG_GUNSHOT_RADIUS_SQ  {float(GUNSHOT_RADIUS)**2:.6f}f\n",
    f"#define CFG_ENEMY_MEMORY_TICKS {ENEMY_MEMORY_TICKS}\n",
    f"#define CFG_STALE_MEMORY_TICK  {STALE_MEMORY_TICK}\n",
    f"#define CFG_MAX_TURN_SPEED   {float(MAX_TURN_SPEED_RAD):.6f}f\n",
    "\n",
    _arr_int32(grid_flat, "NAV_RASTER_GRID"),
    _arr_int8(vis_flat, "NAV_VIS_MATRIX"),
    _arr_int8(adj_flat, "NAV_ADJACENCY"),
    _arr_float(cxy_flat, "NAV_CENTROID_XY"),
    _arr_int32(aids_flat, "NAV_AREA_IDS"),
    _arr_int8(bm_flat, "NAV_BOMBSITE_MASK"),
    _arr_int8(bi_flat, "NAV_BOMBSITE_BY_IDX"),
    _arr_float(bd_flat, "NAV_BOMBSITE_DIST"),
                                                                                # Verticality batch — referenced by cs2_movement.h _resolve_xy_collision cliff guard
                                                                                # and cs2_combat.h 3D hit-test (Batch 3.5 T5).
    _arr_float(cz_flat, "NAV_CENTROIDS_Z"),
    _arr_int8(isr_flat, "NAV_IS_RAMP"),
    _arr_float(area_bounds.flatten(), "NAV_AREA_BOUNDS"),
    _arr_float(delta_x, "NAV_DELTA_X"),
    _arr_float(delta_y, "NAV_DELTA_Y"),
    _arr_float(dir_facing, "NAV_DIR_FACING"),
    _arr_int32(t_spawns, "NAV_T_SPAWNS"),
    _arr_int32(ct_spawns, "NAV_CT_SPAWNS"),
]

# The C package's own directory (cs2_demo.c's `#include "nav_data.h"`), never a restated
# path: a stale one would write the header into a recreated directory, silently, and leave
# the real one old.
out = SOURCE_DIR / "nav_data.h"
out.write_text("".join(lines))
print(f"Written: {out}  (N={md.N}, grid={W}x{H})")
